---
title: "rvest Introduction"
author: "Reed College, Instructional Technology Services"
output: html_document
---

We can use the rvest package to scrape information from the internet into R.  
For example, this [page](http://www.reed.edu/ir/geographic_states.html) on Reed College's Institutional Research website contains a large table with data that we may want to analyze.  Instead of trying to copy this data into Excel or having to manually recreate it, we can use rvest to pull the information directly into R.


```{r, warning=FALSE}

# install packages 
pkg <- c("rvest", "dplyr",  "reshape2", "googleVis",  "magrittr")

new.pkg <- pkg[!(pkg %in% installed.packages())]

if (length(new.pkg)) {
  install.packages(new.pkg)
}


# load packages 
suppressMessages(library(rvest))
suppressMessages(library(dplyr))
suppressMessages(library(reshape2))
suppressMessages(library(googleVis))

# helpful resources for using rvest 
  # vignette("selectorgadget")
  # http://blog.rstudio.org/2014/11/24/rvest-easy-web-scraping-with-r/
```

**Read in data**
```{r}

# download html file
webpage <- html("http://www.reed.edu/ir/geographic_states.html")

# the data we want is in the first table on this page
# the html_table() command coerces the data into a data frame
webpage %>%
  html_nodes("table") %>%
  .[[1]] %>%
  html_table()
```

```{r, warning=FALSE}
# repeat above code but store results in a data frame
data <- 
webpage %>%
  html_nodes("table") %>%
  .[[1]] %>%
  html_table()
```


```{r, warning=FALSE}
# we can now work with this data from the web as a data frame in R
# remove total row from data 
data <- 
  data %>% 
  filter(State!='Total')

# reshape data for plotting 
data_long <- melt(data, id='State')

# rename columns in long data frame 
colnames(data_long) <- c('State', 'Year', 'Matriculants')

# create and manipulate variables for plotting
data_long$Year <- as.numeric(as.character(data_long$Year))
data_long$year <- data_long$Year
data_long$state <- data_long$State




```

```{r, results='asis'}
# plot data 
gvisMotionChart(data_long, "state", "year",
                yvar="Matriculants", xvar="Year",
                colorvar="State")



```


